FROM openresty/openresty:1.25.3.2-alpine

RUN apk add --no-cache python3 py3-pip && \
    rm -f /etc/nginx/conf.d/default.conf

COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

COPY http_server.py /app/http_server.py
COPY nginx.conf /etc/nginx/nginx.conf
COPY lua/proxy.lua /etc/nginx/lua/proxy.lua
COPY start.sh /start.sh
RUN chmod +x /start.sh

WORKDIR /app

EXPOSE 80 8001

CMD ["/start.sh"]
