server:
  address: "0.0.0.0:%d"
  global-rounds: %d

strategy:
  fraction-fit: 1.0
  fraction-evaluate: 1.0
  min-fit-clients: %d
  min-evaluate-clients: %d
  min-available-clients: %d
  aom-rounds-treshold: %d
  aom-selection-enabled: %v
  inflight-threshold: %f

urls:
  metric-server-url: "%s"

paths:
  dataset-dir: "%s"
  model-file: "%s"
