server:
  address: "0.0.0.0:8080"
  global-rounds: 2

strategy:
  fraction-fit: 1.0
  fraction-evaluate: 1.0
  min-fit-clients: 2
  min-evaluate-clients: 2
  min-available-clients: 2
  aom-rounds-treshold: 3

urls:
  metric-server-url: "http://localhost:8001"

paths:
  dataset-dir: "/data"
  model-file: "/model/model.pt"
  state-file: "/model/state.json"
