package common

// Container images
const FL_CLIENT_IMAGE = "leontisljaric/hfl-client:0.1"
const LOCAL_AGGRETATOR_IMAGE = "cilicivan96/hfl-local-server:0.2"
const GLOBAL_AGGRETATOR_IMAGE = "leontisljaric/hfl-global-server:0.1"

const GLOBAL_AGGREGATOR_SERVING_IMAGE = "leontisljaric/hfl-serving:0.1"
const CLIENT_SERVING_IMAGE = "leontisljaric/hfl-serving:0.1"
const LOCAL_AGGREGATOR_SERVING_IMAGE = "leontisljaric/hfl-serving:0.1"

// FL Client configs
const FL_CLIENT_DEPLOYMENT_PREFIX = "fl-cl"
const FL_CLIENT_CONFIG_MOUNT_PATH = "/home/"
const FL_CLIENT_CONFIG_MAP_PREFIX = "fl-cl-cm"
const FL_CLIENT_PERSISTENT_VOLUME_PREFIX = "fl-cl-pv"
const FL_CLIENT_PERSISTENT_VOLUME_CLAIM_PREFIX = "fl-cl-pvc"
const FL_CLIENT_CPU_REQUEST = 0.5
const FL_CLIENT_SERVING_PORT = 8000
const FL_CLIENT_SERVING_NODE_PORT = 30080
const FL_CLIENT_SERVING_DEPLOYMENT_PREFIX = "fl-cl-serving"
const FL_CLIENT_SERVING_CONFIG_MAP_PREFIX = "fl-cl-serving-cm"
const FL_CLIENT_SERVING_SERVICE_PREFIX = "fl-cl-serving-svc"

// GA configs
const GLOBAL_AGGRETATOR_DEPLOYMENT_PREFIX = "fl-ga"
const GLOBAL_AGGRETATOR_MOUNT_PATH = "/home/"
const GLOBAL_AGGREGATOR_SERVICE_PREFIX = "fl-ga-svc"
const GLOBAL_AGGREGATOR_CONFIG_MAP_PREFIX = "fl-ga-cm"
const GLOBAL_AGGREGATOR_PERSISTENT_VOLUME_PREFIX = "fl-ga-pv"
const GLOBAL_AGGREGATOR_PERSISTENT_VOLUME_CLAIM_PREFIX = "fl-ga-pvc"
const GLOBAL_AGGREGATOR_PORT = 8080
const GLOBAL_AGGREGATOR_ROUNDS = 100
const GLOBAL_AGGREGATOR_SERVING_PORT = 8000
const GLOBAL_AGGREGATOR_SERVING_NODE_PORT = 30080
const GLOBAL_AGGREGATOR_SERVING_DEPLOYMENT_PREFIX = "fl-ga-serving"
const GLOBAL_AGGREGATOR_SERVING_CONFIG_MAP_PREFIX = "fl-ga-serving-cm"
const GLOBAL_AGGREGATOR_SERVING_SERVICE_PREFIX = "fl-ga-serving-svc"

// LA configs
const LOCAL_AGGRETATOR_DEPLOYMENT_PREFIX = "fl-la"
const LOCAL_AGGRETATOR_MOUNT_PATH = "/home/"
const LOCAL_AGGREGATOR_SERVICE_PREFIX = "fl-la-svc"
const LOCAL_AGGREGATOR_CONFIG_MAP_PREFIX = "fl-la-cm"
const LOCAL_AGGREGATOR_PERSISTENT_VOLUME_PREFIX = "fl-la-pv"
const LOCAL_AGGREGATOR_PERSISTENT_VOLUME_CLAIM_PREFIX = "fl-la-pvc"
const LOCAL_AGGREGATOR_PORT = 8080
const LOCAL_AGGREGATOR_ROUNDS = 100
const LOCAL_AGGREGATOR_SERVING_PORT = 8000
const LOCAL_AGGREGATOR_SERVING_NODE_PORT = 30080
const LOCAL_AGGREGATOR_SERVING_DEPLOYMENT_PREFIX = "fl-la-serving"
const LOCAL_AGGREGATOR_SERVING_CONFIG_MAP_PREFIX = "fl-la-serving-cm"
const LOCAL_AGGREGATOR_SERVING_SERVICE_PREFIX = "fl-la-serving-svc"

// Persistent Volume path
const PERSISTENT_VOLUME_PATH = "/mnt/aiotwin/hfl_model"

// FL types
const FL_TYPE_CLIENT = "client"
const FL_TYPE_LOCAL_AGGREGATOR = "local_aggregator"
const FL_TYPE_GLOBAL_AGGREGATOR = "global_aggregator"

// Events
const NODE_STATE_CHANGE_EVENT_TYPE = "NodeStateChanged"
const FL_FINISHED_EVENT_TYPE = "FlFinished"

// Node states
const NODE_ADDED = "ADDED"
const NODE_REMOVED = "REMOVED"
